# Generated by Django 4.0 on 2021-12-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_files',
            name='User_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
