# Generated by Django 3.1.13 on 2022-01-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_files_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_files',
            name='User_file',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_files',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
