# Generated by Django 3.1.13 on 2022-01-06 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220104_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_files',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_files',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
